# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!
target 'WarMachine' do
    pod "SAParallaxViewControllerSwift"
    pod "EZSwiftExtensions"
    pod "Gifu"
end

target 'WarMachineTests' do

end

target 'WarMachineUITests' do

end

